version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
  user-project:
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgresd
